### ISSUE TITLE
t4-enumerable-methods

### ISSUE THREAD

**Issue by jeder28** [dcr8898/dcr8898.github.io#1]
Hey Damien,
I really enjoyed your explanation on the enumerable module. Your description is a clear illustration of what it is and how to use it. Your explanations of the three enumerable methods were straight forward and concise. Tying in the accountability group challenge with the group_by method was a great choice and helped me understand it better! I can't really think of any feedback that would actionable since this blog was so helpful! Keep up the great work!

-Heather

**Comment by dcr8898** [comment]
@jeder28 Thanks for the feedback. :)
