### ISSUE TITLE
t6-oop-concepts.html

### ISSUE THREAD

**Issue by aklap** [dcr8898/dcr8898.github.io#2]
Damian, I think your grasp of the concepts and knowledge really came through in your writing. I hadn't thought of modules as being part of DRY but it makes perfect sense. Like you, I'm more of a word person and I think we both might consider amending our posts to add example code or visual aids for people that have a hard time with the abstract nature of these concepts and might benefit from additional presentations of  modules, classes, and objects in action. Otherwise, great job and I look forward to reading you next post.

**Comment by dcr8898** [comment]
Thanks, Alexis! :)
